Feature/crud dos produtos
leandrovi/moderacompra-backend pull request #12
Opened 2021-03-30 20:56 UTC by MarceloMax50

Criação da base do Crud de produtos

2021-03-30 21:17 UTC, brbrq0021 submitted a review, later dismissed

2021-03-30 21:21 UTC, AldaniloSilva submitted a review, later dismissed

2021-03-30 22:25 UTC, leandrovi commented on src/controllers/ProductController.ts
> +            let product = request.body;
**sugestão**: acho que vale a pena desestruturar o `request.body` tipango como `ProductEntity` para pegar sempre os parametros certos (evitando sujeira do frontend), mais ou menos assim:

```ts
const { id, name } = request.body;
```

2021-03-30 22:38 UTC, leandrovi requested changes

2021-03-30 22:38 UTC, leandrovi commented on src/controllers/ProductController.ts
> +            return response.json({ ok: result });
**sugestão**: aqui você pode retornar o resultado direto.. talvez seja bacana usar um nome com mais significado, por exemplo:

```ts
// Aqui pegamos só o "name" porque nao precisamos do "id" para criar um novo produto
const { name }: ProductEntity = request.body;

const product = await service.create({ id, name });

return response.json(product);
```

2021-03-30 22:38 UTC, leandrovi commented on src/controllers/ProductQuantityController.ts
> +            return response.json({ ok: result });
**sugestão**: mesma ideia que comentei no `ProductController.ts`.. que tal uma abordagem mais nessa linha: 

```ts
const {
  list_id,
  product_id,
  initial_quantity,
  final_quantity,
  suggestion_quantity
}: ProductQuantityEntity = request.body;

const productQuantity = await service.create({
  list_id,
  product_id,
  initial_quantity,
  final_quantity,
  suggestion_quantity
});

return response.json(productQuantity);
```

2021-03-30 22:38 UTC, leandrovi commented on src/entities/ProductEntity.ts
> +    public name?: string;
**alteração**: acho que nesse caso o `name` é obrigatório, então não deveria ter a condicional de nulo `?`:

```ts
export class ProductEntity {
    public id?: string;
    public name: string;
}
```

2021-03-30 22:38 UTC, leandrovi commented on src/entities/ProductQuantityEntity.ts
> +    public suggestion_quantity: number;
**alteração**: aqui nesse caso acho que só `initial_quantity` deveria ser obrigatório.. porque tipo, quando a lista inicial for criada, a gente não vai ter uma sugestão ainda.

2021-03-31 02:33 UTC, leandrovi approved these changes

2021-03-31 23:48 UTC, brunoclaumari approved these changes

2021-04-01 00:02 UTC, merged