Feature/close methode for new list
leandrovi/moderacompra-backend pull request #40
Opened 2021-05-20 00:33 UTC by MarceloMax50

2021-05-21 00:53 UTC, leandrovi requested changes

2021-05-21 00:53 UTC, leandrovi commented on src/controllers/ProductQuantityController.ts
> +      const suggestionQttUpdate = await service.updateSugestion(finalQttUpdate);
**alteração simples**: se escreve "suggestion", com duas letras "g".. precisa arrumar aqui e no service: `service.updateSuggestion`

**sugestão**: acho que fica mais semântico chamar de `newProductQuantities` (ou newProductQttList, como preferir), em vez de `suggestionQttUpdate`.

2021-05-21 00:53 UTC, leandrovi commented on src/controllers/ProductQuantityController.ts
> +      const finalQttUpdate = await service.updateBatch(productQttList);
**sugestão**: acho que nesse caso ficaria mais semântico dizer `updatedProductQttList` em vez de `finalQttUpdate`, já que tinhamos um productQttList que passou por um update 🤣

2021-05-21 00:53 UTC, leandrovi commented on src/services/ProductQuantityService.ts
> +      var suggestionQtt =
**sugestão**: aqui pode ser um `const` em vez de `var`, já que uma nova instância do suggestionQtt vai ser criada a cada iteração do loop.

2021-05-21 00:53 UTC, leandrovi commented on src/services/ProductQuantityService.ts
> +      suggestionQttList.push({
**sugestão**: eu quebraria uma linha antes da linha 110 (a linha do push), só pra ficar mais clean para enxergar o que ta rolando.

2021-05-21 00:53 UTC, leandrovi commented on src/services/ProductQuantityService.ts
> +        (productQuantity.initial_quantity - productQuantity.final_quantity);
**correção**: acho que a lógica deveria ser a partir da subtração da quantidade final,  o que você acha?

Por exemplo:
- O cara comprou 4 lampadas em Janeiro (`initial_quantity = 4`)
- Porém, sobrou 1 lampada (`final_quantity = 1`)

Na hora de calcular a sugestão:
- Quantidade final é 1 lampada (ou seja, isso é o que sobrou)
- O que foi consumido (inicial menos final) foram 3 lampadas (`let consumedQuantity = 3`)

Pela lógica, a gente teria que entao sugerir 3 lampadas, já que ele só consumiu 3 lampadas.
Porém não podemos equecer que sobrou uma lampada no `final_quantity = 1`.

Então a gente sabe que ele precisa de 3 lâmpadas, e ele já tem uma lâmpada sobrando.. então ele só precisa comprar 2 lâmpadas dessa vez (`suggestion_quantity = 2`);

Ou seja, eu consigo enxergar o seguinte algoritmo:

```ts
const initial = productQuantity.initial_quantity; // result: 4
const final = productQuantity.final_quantity; // result: 1
const consumed = intial - final; // result: 3
const suggestion = consumed - final; // result: 2
```

2021-05-21 22:37 UTC, MarceloMax50 commented on src/controllers/ProductQuantityController.ts
> +      const suggestionQttUpdate = await service.updateSugestion(finalQttUpdate);
Ajustado!

2021-05-21 22:37 UTC, MarceloMax50 commented on src/controllers/ProductQuantityController.ts
> +      const finalQttUpdate = await service.updateBatch(productQttList);
Ajustado!

2021-05-21 22:37 UTC, MarceloMax50 commented on src/services/ProductQuantityService.ts
> +      var suggestionQtt =
Ajustado!

2021-05-21 22:37 UTC, MarceloMax50 commented on src/services/ProductQuantityService.ts
> +      suggestionQttList.push({
Ajustado!

2021-05-21 22:37 UTC, MarceloMax50 commented on src/services/ProductQuantityService.ts
> +        (productQuantity.initial_quantity - productQuantity.final_quantity);
Ajustado!

2021-05-23 12:29 UTC, leandrovi approved these changes

2021-05-23 12:29 UTC, merged