Session service
leandrovi/moderacompra-backend pull request #41
Opened 2021-05-20 01:42 UTC by MarceloMax50

2021-05-21 00:56 UTC, leandrovi requested changes

2021-05-21 00:56 UTC, leandrovi commented on src/services/SessionService.ts
> +import { error } from "console";
**correção**: esse `error` a gente nao utiliza, já vi ele outras vezes aqui, pode remover man =)

2021-05-21 00:56 UTC, leandrovi commented on src/services/SessionService.ts
> +      throw error(401);
**correção**: a maneira de lançar uma nova exceção é:

```ts
throw new Error(401);
```

`Error` (com "E" maiúsculo) é uma classe global do javascript, você não precisa importar nada.

2021-05-21 23:04 UTC, MarceloMax50 commented on src/services/SessionService.ts
> +import { error } from "console";
Ajustado!

2021-05-21 23:04 UTC, MarceloMax50 commented on src/services/SessionService.ts
> +      throw error(401);
Ajustado!

2021-05-23 17:24 UTC, leandrovi approved these changes

2021-05-23 17:24 UTC, merged